### ISSUE TITLE
Unable to Launch freeRouter control plane along side TOFINO P4 dataplane from [ #004 ] - Cookbook

### ISSUE THREAD

**Issue by ghost** [rare-freertr/validated-design#2]
We have tried to follow the [ #004 ] - Cookbook guide https://wiki.geant.org/pages/viewpage.action?pageId=148084243 and we have the following 2 problems:
Problem 1:  Launching the command  ./pcapInt.bin veth251 22709 127.0.0.1 22710 127.0.0.1 gives us the following error
./pcapInt.bin: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by ./pcapInt.bin). When we issue the command:
"ldd --version" we have version 2.31. 
Problem 2:
At the final step, where we launch RARE bf_forwarder.py with the following command: "./bf_forwarder.py --ifmibs-dir ~/rare-run/mibs/ --ifindex ~/rare-run/snmp/ifindex". We get the error:
Traceback (most recent call last):
  File "./bf_forwarder.py", line 21, in <module>
    from rare.bf_gbl_env.cst_env import *
  File "/rare/bfrt_python/rare/bf_gbl_env/cst_env.py", line 1, in <module>
    from .var_env import *
  File "/rare/bfrt_python/rare/bf_gbl_env/var_env.py", line 26, in <module>
    import bfrt_grpc.client as gc
ModuleNotFoundError: No module named 'bfrt_grpc'
It seems like it has something to do with missing libraries in python as this path
does not exists in our vm /lib/python*/site-packages/tofino/bfrt_grpc/ (not for python3.8 or python3.9)

**Comment by frederic-loui** [comment]
Problem 1:

Which OK are you using ? The blog article is quite old but should still be relevant regarding the latest distribution.
Latest distribution has switched to recent libc such as Debian SID. I suggest you download using:

```
wget www.freertr.org/rtr-`uname -m`.tar
```
and use Debian SID.

If you don't want to use prebuild, you would need to compile `pcapInt.bin`
Before compilation please make sure you have `libpcap-dev` package installed

```
git clone https://github.com/rare-freertr/freeRtr.git
cd freeRtr/misc/native
./c.sh
```
then navigate to  `../../binTmp` you should see `pcapInt.bin` for your platform.

Problem 2:

Seems to show that you your INTEL SDE environment is not set properly. (bf_forwarder.py does not find grpc client.py in SDE library) In that case I would refer to INTEL SDE documentation and try to write a dummy python script that yield package within `bfrt_grpc` folder. Also I would suggest you use latest Debian SID so that python3 is standard.

Now, I suggest you use latest INTEL SDE (e.g 9.12.x) as it is more `python3` friendly

**Comment by ghost** [comment]
Hey Frederic thank you for your answer. We have installed Debian SID, which helped us solve the issue about the incorrect glibC version. It now works fine. :)
We fixed problem 2, but now we would like to create a network topology to test a basic forwading, and using this guide: 
![image](https://github.com/rare-freertr/validated-design/assets/102020598/64ed1e01-819f-4413-8300-4545093686d2)
As seen on this picture: 
![SudoMake](https://github.com/rare-freertr/validated-design/assets/102020598/31de5403-49ad-4951-bc8f-630b076cdf92)

it seems like it is unable to run the 'make' command. Any idea

Thank you very much
